name: "PR Checklist to Sheets"
description: "Parse PR body checklists by reviewer and append them to Google Sheets, then post the sheet link back to the PR"
author: ""
branding:
  color: "blue"
  icon: "check-circle"
inputs:
  google-service-account-key:
    description: "Base64-encoded service account JSON with Sheets access. Required if not using OIDC authentication."
    required: false
    default: ""
  workload-identity-provider:
    description: "Workload Identity Provider resource name for OIDC authentication (e.g., projects/123456/locations/global/workloadIdentityPools/my-pool/providers/my-provider)"
    required: false
    default: ""
  service-account-email:
    description: "Service account email for OIDC authentication (e.g., my-sa@my-project.iam.gserviceaccount.com)"
    required: false
    default: ""
  google-client-id:
    description: "OAuth 2.0 Client ID for user OAuth authentication"
    required: false
    default: ""
  google-client-secret:
    description: "OAuth 2.0 Client Secret for user OAuth authentication"
    required: false
    default: ""
  google-refresh-token:
    description: "OAuth 2.0 Refresh Token obtained from user consent flow"
    required: false
    default: ""
  sheet-id:
    description: "Target Google Spreadsheet ID"
    required: true
  sheet-range:
    description: "Starting cell within the newly created date-named sheet (e.g. A1, default A1). Sheet name is generated automatically per run."
    default: "A1"
  checklist-start-marker:
    description: "HTML comment marker for checklist start (default: <!-- checklist -->)"
    default: "<!-- checklist -->"
  checklist-end-marker:
    description: "HTML comment marker for checklist end (default: <!-- checklist end -->)"
    default: "<!-- checklist end -->"
  members-config-path:
    description: "Path to YAML file containing members list"
    default: "members.yaml"
  append-pr-link:
    description: "Whether to append sheet link into PR body (true/false)"
    default: "true"
  sheet-link-text:
    description: "Custom text for the sheet link added to the PR body"
    default: "Checklist synced to Google Sheets"
  from-ref:
    description: "Git ref (commit hash, tag, or branch) to start collecting PRs from. Defaults to the latest tag."
    required: false
    default: ""
  to-ref:
    description: "Git ref (commit hash, tag, or branch) to collect PRs up to. Defaults to the current PR's head."
    required: false
    default: ""
runs:
  using: "node20"
  main: "dist/index.js"
